generation_params_medium:
  temperature: 0.9  # "креативность" модели
  top_k: 4  # Количество токенов для сортировки по вероятности
  top_p: 0.5  # Сумма вероятностей первых вариантов
  num_beams: 7  # Количество путей поиска (выборка лучшего варианта)
  repetition_penalty: 5.0 # Штраф за повторение токенов
  do_sample: True # Использование методы выборки
  no_repeat_ngram_size: 3 # Запрет на повторение триграмм

generation_params_big:
  temperature: 1.5  # "креативность" модели
  top_k: 20  # Количество токенов для сортировки по вероятности
  top_p: 0.7  # Сумма вероятностей первых вариантов
  num_beams: 7  # Количество путей поиска (выборка лучшего варианта)
  repetition_penalty: 5.0 # Штраф за повторение токенов
  do_sample: True # Использование методы выборки
  no_repeat_ngram_size: 3 # Запрет на повторение триграмм